# -----------------------------------------------------------------------------
# General seimbol parameters
# -----------------------------------------------------------------------------

# Enable TLS via certmanager
tls:
  enabled: true

# -----------------------------------------------------------------------------
# Alerting parameters
# -----------------------------------------------------------------------------

alerting:
  deploy:
    topology:
      name: alerting-deploy-topology
      image:
        repository: gresearchdev/siembol-alerting-storm
        tag: latest
        pullPolicy: Always
    rules:
      name: alerting-deploy-rules

# -----------------------------------------------------------------------------
# ZooKeeper parameters
# -----------------------------------------------------------------------------

zookeeper:
  ## If `zookeeper.enabled: false`, the `servers` value must be set.
  ## `storm.zookeeper.servers` and `kafka.externalZookeeper.servers`
  ## should be updated to match this value.
  ## If `zookeeper.enabled: true`, this chart will spin up ZooKeeper 
  ## service with the default name: "{{ .Release.Name }}-zookeeper".
  ## The Storm and Kafka sub-charts will use this same service by 
  ## using the default values below.
  enabled: true 
  # servers: "ext-zk-zookeeper"
  image:
    registry: docker.io
    repository: bitnami/zookeeper
    tag: 3.7.0-debian-10-r0
    pullPolicy: Always

# -----------------------------------------------------------------------------
# Storm parameters
# -----------------------------------------------------------------------------

storm:
  # disable Storm's ZooKeeper and use a templatized value to use Siembol's zk
  zookeeper:
    enabled: false 
    # This value will be evaluated in the context of the Storm sub-chart
    servers: ["{{ .Release.Name }}-zookeeper"]
  ingress:
    enabled: true
    hostname: storm.siembol.local

# -----------------------------------------------------------------------------
# Kafka parameters
# -----------------------------------------------------------------------------

kafka:
  persistence:
    enabled: false
  # disable Kafka's ZooKeeper and use a templatized value to use Siembol's zk
  zookeeper:
    enabled: false
  externalZookeeper:
    # This value will be evaluated in the context of the Kafka sub-chart
    servers: ["{{ .Release.Name }}-zookeeper"]

# -----------------------------------------------------------------------------
# config-editor-rest parameters
# -----------------------------------------------------------------------------

rest:
  image: 
    repository: "gresearchdev/siembol-config-editor-rest"
    tag: "1.1.0"
    pullPolicy: Always

  appName: "config-editor-rest"
  applicationProperties: "resources/application.properties"
  gitConfig: "resources/git.config"
  mountPath: "/opt/config-editor-rest"

  ingress:
    enabled: true
    hostname: rest.siembol.local

# -----------------------------------------------------------------------------
# config-editor-ui parameters
# -----------------------------------------------------------------------------

ui:
  image: 
    repository: "gresearchdev/siembol-config-editor-ui"
    tag: "latest"
    pullPolicy: Always

  appName: config-editor-ui

  # Run with an ingress
  ingress:
    enabled: true
    hostname: ui.siembol.local

# -----------------------------------------------------------------------------
# storm-topology-manager parameters
# -----------------------------------------------------------------------------

manager:
  appName: "storm-topology-manager"
  serviceAccount: "storm-topology-manager"
  image: 
    repository: "gresearchdev/siembol-storm-topology-manager"
    tag: "latest"
    pullPolicy: Always

  applicationProperties: "resources/application.manager.properties"
  stormSubmit: "resources/storm-submit.yaml"
  mountPath: "/opt/storm-topology-manager"

  # Run with an ingress
  ingress:
    enabled: true
    hostname: manager.siembol.local